[package]
name = "polars_advancet_teorie"
version = "0.1.0"
edition = "2024"

[lib]
name = "polars_advancet_teorie"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "polars_advancet_teorie_cli"
path = "src/main.rs"


[dependencies]
anyhow = "1.0.104"
polars =  { version = "0.55.2", features = ["lazy", "parquet", "json", "temporal", "fmt"] }

[dev-dependencies]
tempfile = "3.27.0"